version: '3'
services:
    node:
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
        environment:
            - NODE_ENV=production
        working_dir: /app
        ports:
            - '3000:3000'
        restart: always
