version: '3'
services:
    node:
        image: node:16.17.1
        environment:
            - NODE_ENV=development
        volumes:
            - ../:/usr/src/app
        working_dir: /usr/src/app
        ports:
            - '3000:3000'
        tty: true
